# Generated by Django 5.2.9 on 2025-12-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exchangerate_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='target',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Healthcare', 'Healthcare'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(max_length=255),
        ),
    ]
