# Generated by Django 5.2.9 on 2025-12-17 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_expense_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
