# Generated by Django 5.2.9 on 2025-12-17 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expense_expense_date_alter_expense_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
